# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Desktop/sparrow_pc/linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Desktop/sparrow_pc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/sparrow_pc/CMakeFiles /home/user/Desktop/sparrow_pc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Desktop/sparrow_pc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bitcoin_wallet

# Build rule for target.
bitcoin_wallet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitcoin_wallet
.PHONY : bitcoin_wallet

# fast build rule for target.
bitcoin_wallet/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/build
.PHONY : bitcoin_wallet/fast

#=============================================================================
# Target rules for targets named flutter_assemble

# Build rule for target.
flutter_assemble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flutter_assemble
.PHONY : flutter_assemble

# fast build rule for target.
flutter_assemble/fast:
	$(MAKE) $(MAKESILENT) -f flutter/CMakeFiles/flutter_assemble.dir/build.make flutter/CMakeFiles/flutter_assemble.dir/build
.PHONY : flutter_assemble/fast

#=============================================================================
# Target rules for targets named url_launcher_linux_plugin

# Build rule for target.
url_launcher_linux_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 url_launcher_linux_plugin
.PHONY : url_launcher_linux_plugin

# fast build rule for target.
url_launcher_linux_plugin/fast:
	$(MAKE) $(MAKESILENT) -f plugins/url_launcher_linux/CMakeFiles/url_launcher_linux_plugin.dir/build.make plugins/url_launcher_linux/CMakeFiles/url_launcher_linux_plugin.dir/build
.PHONY : url_launcher_linux_plugin/fast

#=============================================================================
# Target rules for targets named window_size_plugin

# Build rule for target.
window_size_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window_size_plugin
.PHONY : window_size_plugin

# fast build rule for target.
window_size_plugin/fast:
	$(MAKE) $(MAKESILENT) -f plugins/window_size/CMakeFiles/window_size_plugin.dir/build.make plugins/window_size/CMakeFiles/window_size_plugin.dir/build
.PHONY : window_size_plugin/fast

flutter/generated_plugin_registrant.o: flutter/generated_plugin_registrant.cc.o
.PHONY : flutter/generated_plugin_registrant.o

# target to build an object file
flutter/generated_plugin_registrant.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/flutter/generated_plugin_registrant.cc.o
.PHONY : flutter/generated_plugin_registrant.cc.o

flutter/generated_plugin_registrant.i: flutter/generated_plugin_registrant.cc.i
.PHONY : flutter/generated_plugin_registrant.i

# target to preprocess a source file
flutter/generated_plugin_registrant.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/flutter/generated_plugin_registrant.cc.i
.PHONY : flutter/generated_plugin_registrant.cc.i

flutter/generated_plugin_registrant.s: flutter/generated_plugin_registrant.cc.s
.PHONY : flutter/generated_plugin_registrant.s

# target to generate assembly for a file
flutter/generated_plugin_registrant.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/flutter/generated_plugin_registrant.cc.s
.PHONY : flutter/generated_plugin_registrant.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/main.cc.s
.PHONY : main.cc.s

bitcoin_wallet.o: bitcoin_wallet.cc.o
.PHONY : bitcoin_wallet.o

# target to build an object file
bitcoin_wallet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/bitcoin_wallet.cc.o
.PHONY : bitcoin_wallet.cc.o

bitcoin_wallet.i: bitcoin_wallet.cc.i
.PHONY : bitcoin_wallet.i

# target to preprocess a source file
bitcoin_wallet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/bitcoin_wallet.cc.i
.PHONY : bitcoin_wallet.cc.i

bitcoin_wallet.s: bitcoin_wallet.cc.s
.PHONY : bitcoin_wallet.s

# target to generate assembly for a file
bitcoin_wallet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitcoin_wallet.dir/build.make CMakeFiles/bitcoin_wallet.dir/bitcoin_wallet.cc.s
.PHONY : bitcoin_wallet.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... flutter_assemble"
	@echo "... bitcoin_wallet"
	@echo "... url_launcher_linux_plugin"
	@echo "... window_size_plugin"
	@echo "... flutter/generated_plugin_registrant.o"
	@echo "... flutter/generated_plugin_registrant.i"
	@echo "... flutter/generated_plugin_registrant.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... bitcoin_wallet.o"
	@echo "... bitcoin_wallet.i"
	@echo "... bitcoin_wallet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

